[build]
  command = "ng build --configuration=production"
  publish = "dist/ecard/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
  publish_directory = "dist/ecard/browser"
